package wol

// WARNING: Auto generated version file. Do not edit this file by hand.
// WARNING: go get github.com/sabhiram/gover to manage this file.
// Version: 2.0.0
const (
	Major = 2
	Minor = 0
	Patch = 0

	Version = "2.0.0"
)
