package main

// WARNING: Auto generated version file. Do not edit this file by hand.
// WARNING: go get github.com/sabhiram/gover to manage this file.
// Version: 1.0.3

const (
    Major = 1
    Minor = 0
    Patch = 3

    Version = "1.0.3"
)
